volumes:
  quran_backend_local_postgres_data: {}
  quran_backend_local_postgres_data_backups: {}
  quran_backend_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: quran_backend_local_django
    container_name: quran_backend_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: quran_backend_production_postgres
    container_name: quran_backend_local_postgres
    volumes:
      - quran_backend_local_postgres_data:/var/lib/postgresql/data
      - quran_backend_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  redis:
    image: docker.io/redis:7.2
    container_name: quran_backend_local_redis
    command: redis-server --maxmemory 500mb --maxmemory-policy allkeys-lru
    volumes:
      - quran_backend_local_redis_data:/data

  celeryworker:
    <<: *django
    image: quran_backend_local_celeryworker
    container_name: quran_backend_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: quran_backend_local_celerybeat
    container_name: quran_backend_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: quran_backend_local_flower
    container_name: quran_backend_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
